name: CI for screenshot
on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
jobs:
  screenshot:
    name: Screenshot
    runs-on: windows-latest
    steps:
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://jajeebkorreebjeeb.vercel.app/
          destination: preview_img.png
      - name: Commit files
        run: 
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: main
