name: CI for screenshot
on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
jobs:
  screenshot:
    name: Screenshot
    steps:
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://jajeebkorreebjeeb.vercel.app/
          destination: public/preview_img.png
